server:
  port: 8890
#  服务名
spring:
  application:
    name: server-vod
  servlet:
    multipart:
      # 最大上传单个文件大小：默认1M
      max-file-size: 1024MB
      # 最大置总上传的数据大小 ：默认10M
      max-request-size: 1024MB

  #nacos地址  springCloud注册中心
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  #  开发环境
  profiles:
    active: dev


#阿里云 vod
#不同的服务器，地址不同
aliyun:
  vod:
    file:
      keyid: LTAI4FyDxdkuFHP2sib3uTqT
      keysecret: L2w7MtNdFscxpxYRF8tffDBv66okJk
