server:
  port: 8888

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/hehe123?characterEncoding=UTF-8
    username: lixing
    password: 123456

    #返回json的全局时间格式
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

    #环境设置dev(开发),test,prod
  profiles:
    active: dev
  application:
    name: service-edu

  #nacos地址  springCloud注册中心
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848


  #mybatis日志
mybatis-plus:
  configration:
    #log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

  mapper-locations: classpath:com/lx/mapper/xml/*Mapper.xml
  global-config:
    db-config:
      logic-delete-field: flag  # 全局逻辑删除的实体字段名(since 3.3.0,配置后可以忽略不配置步骤2)
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)

  type-aliases-package: com.lx.entity

#  开启熔断机制
feign:
  hystrix:
    enabled: true
#    设置hystrix默认时间
    command:
      default:
        execution:
          isolocation:
            thread:
              timeoutInMilliseconds: 6000




